apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: app
  labels:
    app: hello
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
    tier: web
